server:
  port: 56010

spring:
  application:
    name: quickstart-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        server-addr: 10.214.148.22:8848
#        server-addr: 192.168.127.134:8848
#